"""add malenia_event_id to races

Revision ID: b46282beecdd
Revises: ac2b8c72817b
Create Date: 2026-07-04 16:50:09.832750

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b46282beecdd"
down_revision: str | None = "ac2b8c72817b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("races", sa.Column("malenia_event_id", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("races", "malenia_event_id")
    # ### end Alembic commands ###
