# SpeedFog Racing - Base Pool Defaults
# All pools inherit from this. Override any value in your pool file.

[run]
seed = 0
run_complete_message = [
    # Max length:
    #XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    "RUN COMPLETE GG",
    "GG WP",
    "WELL PLAYED",
    "TRY FINGER, BUT HOLE",
    "GIT GUD",
    "SKILL ISSUE RESOLVED",
    "EMBOLDENED BY THE FLAME", # Margit
    "LORD OF ALL THAT IS GOLDEN", # Godrick
    "DEVOURED THE GODS, TOGETHAA", # Rykard
    "A MAN CAN KILL A GOD", # Gideon
    "TARNISHED WARRIOR", # Hoarah Loux
    "HAVE NEVER KNOWN DEFEAT", # Malenia
    "NIHIL! NIHIL! NIHIL!", # Mohg
]
chapel_grace = true
sentry_torch_shop = true

[budget]
tolerance = 5

[structure]
max_parallel_paths = 3
split_probability = 0.9
merge_probability = 0.5
max_entrances = 2
max_exits = 4
min_branch_age = 3
crosslinks = true
start_tier = 3

[starting_items]
academy_key = true
rusty_key = true
pureblood_medal = false
drawing_room_key = true
lantern = true
spirit_calling_bell = true
physick_flask = true
great_runes = true
whetstone_knife = true
stonesword_keys = 6

# DLC key items (prevent softlocks in DLC areas)
omother = true
welldepthskey = false
gaolupperlevelkey = true
gaollowerlevelkey = true
holeladennecklace = false
messmerskindling = true

[enemy]
randomize_bosses = "none"
ignore_arena_size = false
swap_boss = false

[item_randomizer]
difficulty = 50
enabled = true
remove_requirements = true
auto_upgrade_weapons = true
auto_upgrade_dropped = true
reduce_upgrade_cost = true
dlc = true
item_preset = true
allcraft = true

[plugin.summer]
enabled = true
