# SpeedFog Racing - Standard Pool Configuration
# ~1 hour races
extends = "_base"

[display]
name = "Sunbathing Outdoors"
sort_order = 1
estimated_duration = "~1h"
description = "Only outdoor areas and sunny arenas"

[run]
run_complete_message = [
    "BURN, FOR THE SAKE OF THE NEW LORD"
]

[requirements]
legacy_dungeons = 6
bosses = 2
mini_dungeons = 4
major_bosses = 8
exclude_zones = [
    "academy_chest",
    "academy_library",
    "ainsel",
    "ainsel_abovestart",
    "ainsel_dragonkin",
    "ainsel_start",
    "altus_catacombs",
    "altus_catacombs_boss",
    "altus_elemer",
    "altus_grave_boss",
    "altus_grotto",
    "altus_grotto_boss",
    "altus_lux_boss",
    "altus_oldtunnel",
    "altus_oldtunnel_boss",
    "altus_sagescave",
    "altus_sagescave_boss",
    "altus_sagescave_boss2",
    "altus_tunnel",
    "altus_tunnel_boss",
    "altus_writheblood_boss",
    "caelid_abandonedcave",
    "caelid_abandonedcave_boss",
    "caelid_abandonedcave_start",
    "caelid_caelem_boss",
    "caelid_catacombs",
    "caelid_catacombs_boss",
    "caelid_crypt_boss",
    "caelid_erdtreecatacombs",
    "caelid_erdtreecatacombs_boss",
    "caelid_gaeltunnel",
    "caelid_gaeltunnel_boss",
    "caelid_gaeltunnel_rear",
    "caelid_gaeltunnel_start",
    "caelid_gaolcave",
    "caelid_gaolcave_boss",
    "caelid_gaolcave_preboss",
    "caelid_selliatunnel",
    "caelid_selliatunnel_boss",
    "caelid_tower_boss",
    "caelid_wardead",
    "caelid_wardead_boss",
    "charo_gaol",
    "charo_gaol_boss",
    "charo_gaol_lower",
    "charo_gaol_preboss",
    "dragonbarrow_cave",
    "dragonbarrow_cave_boss",
    "dragonbarrow_cave_preboss",
    "dragonbarrow_selliahideaway",
    "dragonbarrow_selliahideaway_boss",
    "ellac_cave",
    "ellac_cave_boss",
    #"farumazula_godskinduo",
    "flamepeak_grave",
    "flamepeak_grave_boss",
    "gelmir_grave",
    "gelmir_grave_boss",
    "gelmir_seethewatercave",
    "gelmir_seethewatercave_boss",
    "gelmir_volcanocave",
    "gelmir_volcanocave_boss",
    "gelmir_wyndhamcatacombs",
    "gelmir_wyndhamcatacombs_boss",
    "gravesite_catacombs",
    "gravesite_catacombs_boss",
    "gravesite_dragonpit",
    "gravesite_dragonpit_boss",
    "gravesite_dragonpit_postboss",
    "gravesite_dragonpit_preboss",
    "gravesite_forge",
    "gravesite_gaol",
    "gravesite_gaol_boss",
    "graveyard",
    "graveyard_cave_boss",
    "graveyard_grave",
    "graveyard_grave_boss",
    #"leyndell2_sanctuary",
    #"leyndell_sanctuary",
    "leyndell_tower_boss",
    "limgrave_coastalcave",
    "limgrave_coastalcave_boss",
    "limgrave_grovesidecave",
    "limgrave_grovesidecave_boss",
    "limgrave_highroadcave",
    "limgrave_highroadcave_boss",
    "limgrave_murkwatercatacombs",
    "limgrave_murkwatercatacombs_boss",
    "limgrave_murkwatercave",
    "limgrave_stormfootcatacombs",
    "limgrave_stormfootcatacombs_boss",
    "limgrave_tunnels",
    "limgrave_tunnels_boss",
    "limgrave_waypoint_boss",
    "liurnia_academycave",
    "liurnia_academycave_boss",
    "liurnia_blackknifecatacombs",
    "liurnia_blackknifecatacombs_boss",
    "liurnia_blackknifecatacombs_boss2",
    "liurnia_cliffbottomcatacombs",
    "liurnia_cliffbottomcatacombs_boss",
    "liurnia_kingsrealm_boss",
    "liurnia_lakesidecave",
    "liurnia_lakesidecave_boss",
    "liurnia_roadsendcatacombs",
    "liurnia_roadsendcatacombs_boss",
    "liurnia_stillwatercave",
    "liurnia_stillwatercave_boss",
    "liurnia_tunnel",
    "liurnia_tunnel_boss",
    "midramanse",
    "midramanse_boss",
    "mountaintops_catacombs",
    "mountaintops_catacombs_boss",
    "mountaintops_cave",
    "mountaintops_cave_boss",
    "outskirts_grave",
    "outskirts_grave_boss",
    "outskirts_sealedtunnel",
    "outskirts_sealedtunnel_boss",
    "outskirts_sealedtunnel_preboss",
    "outskirts_sidetomb_boss",
    "peninsula_earthborecave",
    "peninsula_earthborecave_boss",
    "peninsula_impalerscatacombs",
    "peninsula_impalerscatacombs_boss",
    "peninsula_tombswardcatacombs",
    "peninsula_tombswardcatacombs_boss",
    "peninsula_tombswardcave",
    "peninsula_tombswardcave_boss",
    "peninsula_tunnel",
    "peninsula_tunnel_boss",
    #"precipice_boss",
    "rauhbase_catacombs",
    "rauhbase_catacombs_boss",
    "rauhbase_forge",
    "scadualtus_catacombs",
    "scadualtus_catacombs_boss",
    "scadualtus_forge",
    "scadualtus_gaol",
    "scadualtus_gaol_boss",
    "sewer_catacombs",
    "sewer_catacombs_boss",
    "sewer_mohg",
    "sewer_royal",
    #"shadowkeep_boss",
    #"shadowkeep_church",
    #"shadowkeep_church_lower",
    #"shadowkeep_sanctum",
    #"siofra_boss",
    #"siofra_dragonkin",
    "snowfield_catacombs",
    "snowfield_catacombs_boss",
    "snowfield_cave",
    "snowfield_cave_boss",
    "snowfield_hiddenpath",
    "snowfield_hiddenpath_boss",
    "snowfield_prehiddenpath",
    "snowfield_tunnel",
    "snowfield_tunnel_boss",
    #"storehouse_messmer",
    "stormhill_catacombs",
    "stormhill_catacombs_boss",
    "volcano_abductors",
    #"volcano_rykard",
]

[structure]
max_parallel_paths = 2
layers_count = 22
final_tier = 18
#first_layer_type = "legacy_dungeon"
final_boss_candidates = ["caelid_radahn"]

[starting_items]
whetblades = true
talisman_pouches = 3
golden_seeds = 7
sacred_tears = 4
starting_runes = 40000
larval_tears = 3
stonesword_keys = 6

[care_package]
enabled = true
weapon_upgrade = 25
weapons = 0
shields = 0
catalysts = 2
talismans = 2
sorceries = 2
incantations = 2
head_armor = 1
body_armor = 1
arm_armor = 1
leg_armor = 1
crystal_tears = 5
ashes_of_war = 3

[item_randomizer]
difficulty = 50
nerf_gargoyles = true

[enemy]
randomize_bosses = "all"

[plugin.weather]
enabled = true
weather = "cloudless"
hour = 12
freeze_time = true
